2023-10-26 22:25:17,629 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-10-26 22:25:17,629 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Configure stats pid to 24696
2023-10-26 22:25:17,629 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Loading settings from C:\Users\tobia\.config\wandb\settings
2023-10-26 22:25:17,629 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Loading settings from C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\wandb\settings
2023-10-26 22:25:17,629 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-26 22:25:17,629 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\tobia\\Documents\\GitHub\\RNN_Tobia_Simmler\\main.py'}
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\wandb\run-20231026_222517-2vz8s7bb\logs\debug.log
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\wandb\run-20231026_222517-2vz8s7bb\logs\debug-internal.log
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_init.py:init():547] calling init triggers
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'dataset_name': 'ctxt', 'n_epochs': 2, 'batch_size': 16, 'total_seq_length': 1400, 'seq_length': 1400, 'training_help': 15, 'hidden_dims': 100, 'n_trials': 5, 'with_inputnoise': 1, 'noise_level': 2, 'coherency_intervals': 'uniform', 'optimizer_name': 'SGD', 'lr': 0.0001, 'betas': [0.9, 0.999], 'eps': 1e-07, 'weight_decay': 0.0001, 'amsgrad': False, 'momentum': 0.9, 'apply_gradient_clipping': 1}
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_init.py:init():596] starting backend
2023-10-26 22:25:17,630 INFO    MainThread:24696 [wandb_init.py:init():600] setting up manager
2023-10-26 22:25:17,631 INFO    MainThread:24696 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-10-26 22:25:17,633 INFO    MainThread:24696 [wandb_init.py:init():606] backend started and connected
2023-10-26 22:25:17,633 INFO    MainThread:24696 [wandb_init.py:init():700] updated telemetry
2023-10-26 22:25:17,634 INFO    MainThread:24696 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-10-26 22:25:18,213 INFO    MainThread:24696 [wandb_run.py:_on_init():2177] communicating current version
2023-10-26 22:25:18,420 INFO    MainThread:24696 [wandb_run.py:_on_init():2186] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-26 22:25:18,420 INFO    MainThread:24696 [wandb_init.py:init():787] starting run threads in backend
2023-10-26 22:25:18,459 INFO    MainThread:24696 [wandb_run.py:_console_start():2158] atexit reg
2023-10-26 22:25:18,459 INFO    MainThread:24696 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-10-26 22:25:18,459 INFO    MainThread:24696 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-10-26 22:25:18,459 INFO    MainThread:24696 [wandb_run.py:_redirect():2103] Redirects installed.
2023-10-26 22:25:18,459 INFO    MainThread:24696 [wandb_init.py:init():829] run started, returning control to user process
2023-10-26 22:25:20,790 ERROR   MainThread:24696 [util.py:get_module():226] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\util.py", line 188, in import_module_lazy
    return sys.modules[name]
KeyError: 'plotly.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\util.py", line 221, in get_module
    return import_module_lazy(name)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\util.py", line 190, in import_module_lazy
    module_spec = importlib.util.find_spec(name)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'plotly'
2023-10-26 22:25:28,295 WARNING MsgRouterThr:24696 [router.py:message_loop():77] message_loop has been closed
