  0%|                                                                                                                                                                                               | 0/300 [00:00<?, ?it/s]C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\histograms.py:353: RuntimeWarning:
overflow encountered in subtract
C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\histograms.py:851: RuntimeWarning:
invalid value encountered in multiply
  0%|                                                                                                                                                                                               | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\main.py", line 15, in <module>
    run(config["experiment"])
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\runner.py", line 72, in run
    tm.fit(num_epochs=config["training"]["n_epochs"])
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 94, in fit
    self.create_weights_histogram(cur_epoch, num_epochs)
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 313, in create_weights_histogram
    self.save_histogram(w_in, "w_in", cur_epoch + 1, num_epochs)
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 318, in save_histogram
    plt.hist(weights, bins=50)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 2645, in hist
    return gca().hist(
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 1459, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_axes.py", line 6790, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "<__array_function__ internals>", line 180, in histogram
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\histograms.py", line 857, in histogram
    decrement = tmp_a < bin_edges[indices]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 51
Using device: cpu