
Using device: cpu
  0%|                                                                                                                                                                                           | 0/300 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\main.py", line 15, in <module>
    run(config["experiment"])
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\runner.py", line 70, in run
    tm.fit(num_epochs=config["training"]["n_epochs"])
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 123, in fit
    self.train(gradients, self.n_intervals,self.device, self.train_dataloader, self.step, (self.training_help>cur_epoch) )
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 167, in train
    out, loss, h_1, trial_loss = f(partial_in, partial_tar, train_help, h_1, gradients=gradients, backprop=do_backprop, trial_loss=trial_loss)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 249, in step
    out, loss, h_1 = self.compute_loss(inputs, labels, h_1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_rnn_ext1.py", line 10, in compute_loss
    out, h_1 = self.model(inputs, h_1)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\.conda\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\.conda\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\network\rnn.py", line 109, in forward
    out = self.fc_out(out)
          ^^^^^^^^^^^^^^^^
  File "c:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\.conda\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\.conda\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\.conda\Lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1600x100 and 20x1)